apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: default
# kubectl describe secret $(kubectl get secret | grep admin-user | awk '{print $1}')
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: default
